/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WaitingRoomNavigator {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWaitingRoomNavigatorElement extends Components.WaitingRoomNavigator, HTMLStencilElement {
    }
    var HTMLWaitingRoomNavigatorElement: {
        prototype: HTMLWaitingRoomNavigatorElement;
        new (): HTMLWaitingRoomNavigatorElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "waiting-room-navigator": HTMLWaitingRoomNavigatorElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WaitingRoomNavigator {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "waiting-room-navigator": WaitingRoomNavigator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "waiting-room-navigator": LocalJSX.WaitingRoomNavigator & JSXBase.HTMLAttributes<HTMLWaitingRoomNavigatorElement>;
        }
    }
}
